name: GTA
alpha: 0.8
n_heads: 3 # number of ensemble network for uncertainty estimation
max_repetitions: 1
e_greedy_type: "power" # option: ['inverse', 'linear', 'power'] 
power_value: 8.0 # only used when e_greedy_type is 'power'