defaults:
    - _self_
    - algos: null
    - envs: null

seed: 0
use_wandb: false
group_name: default
total_training_steps: 3000000
use_step_rate: false
eval_interval: 2000 # in step units
eval_max_steps: 100000 # per episode
eval_episodes: 1
warmup_steps: 1000 # in step units

# render should set two flags: 
video_save_dir: null # if null, videos are not saved
log_eval_interval: 100000 # evaluation logging interval: render, action distribution, etc.
display_eval_interval: 100000 # evaluation display interval: render to screen

# model saving
save_model: False
save_dir: ./models/
save_interval: 10000

common_args:
  gamma: 0.99 #discount factor
  lr: 0.001
  batch_size: 64
  rep_batch_size: 128
  buffer_size: 50000
  rep_buffer_size: 500000
  use_lr_decay: false
  use_hard_update: false
  update_interval: 1000 # use only for hard update
  tau: 0.005 # use only for soft update
  e_greedy_type: linear # linear | exponential
  e_decay: 50000 # for exponential decay
  max_epsilon: 1.0
  min_epsilon: 0.0
  use_image: false
  hidden_dim: 512
  use_act_skip_buf: false # whether to use skip buffer in action network training
  prev_buffer_save: false # whether to save previous buffer for skip buffer